### ISSUE TITLE
markdown bin is broken

### ISSUE THREAD

**Issue by jbenet** [shurcooL/markdownfmt#15]
```
> go get github.com/shurcooL/markdownfmt/markdown
# github.com/shurcooL/markdownfmt/markdown
../../shurcooL/markdownfmt/markdown/main.go:429: cannot use markdownRenderer literal (type *markdownRenderer) as type blackfriday.Renderer in return argument:
	*markdownRenderer does not implement blackfriday.Renderer (wrong type for Header method)
		have Header(*bytes.Buffer, func() bool, int, string)
		want Header(*bytes.Buffer, func() bool, int)
```

consider vendoring blackfriday. (**sigh go pkg management...**)

**Comment by shurcooL** [comment]
Hi @jbenet,

`markdownfmt` is designed to work with the latest version of blackfriday package, but it looks like you have a (much) older one. The signature of `Header` changed almost a year ago in russross/blackfriday@2dff0864f0288984446b73c8d9f60fc441f48b3d.

The [correct way](https://github.com/shurcooL/markdownfmt#installation) to install `markdownfmt` is to use the `-u` flag:

```
go get -u github.com/shurcooL/markdownfmt
```

Doing that should fix your issue. Note that it will update your blackfriday library to latest version, which is not API compatible with the version you already have.

> consider vendoring blackfriday. (**sigh go pkg management...**)

I've considered vendoring, but I prefer just supporting the latest versions of all packages.

**Comment by jbenet** [comment]
@shurcooL interesting-- yeah thought i had upgraded blackfriday. the src got updated but i think some of the compiled srcs were installed. anyway, builds now.

> I've considered vendoring, but I prefer just supporting the latest versions of all packages.

Hm, but what happens when you stop maintaining? your code becomes unlikely to be used as others would have to go find the deps (if they even exist at that point). I've had deps disappear under me-- an extreme case is this: https://www.youtube.com/watch?v=K_DIwiSDaT8 

At the very least would be useful to note the last version used of each dep :)

**Comment by shurcooL** [comment]
> At the very least would be useful to note the last version used of each dep :) 

I used to do that. See a160c2d10108f72540a106953db4a5c5812a54e3, 6c9ac26a2897bb9dba87a93bbcced5c3a6bbbd29 and ef52707985c3664f8daae0a964338d27b790a0d2. But then I stopped doing it in 5618223aed7ed55683df93db19402614da38112d. See its commit message for rationale.

> Hm, but what happens when you stop maintaining?

I'm not planning on doing that. I maintain all my code. But when I do stop, I'll either vendor and worry about it then, or just not do anything. If I stop maintaining my code, it's as good as deleted. It will not be helpful (if it is helpful, that's just luck and it will eventually become obsolete). Others are welcome to fork or take ownership if I stop maintaining.

> I've had deps disappear under me

As for dependencies I use, I review them carefully and accept the tradeoffs of not writing code myself. I trust the people who wrote that code. If I didn't trust them, I wouldn't have used their code in the first place (or I would've copied it rather than importing their import path).

If something _really_ unexpected happens (e.g., a critical dependency is removed from GitHub), I have all the Go packages in my local GOPATH workspace, so restoring the deleted repo is trivial.

> anyway, builds now.

Great! :) I will close this.

Dependency management is a non-trivial, interesting subject and I've love to talk more about it if you wish. But I'm having a lot of success with my approach for my personal code.

**Comment by jbenet** [comment]
I respond because i think it's useful to convey my thoughts, hear yours, and provide some feedback/pushback. All of this is -- of course -- [just my opinion](https://www.youtube.com/watch?v=pWdd6_ZxX8c) and you should do whatever works for you and your users. 

> The latest version used is the latest version of each package. That's what I have locally. That's what Travis builds with. That's what everyone gets when they do go get -u. It's very easy. :)

You can lock all of these things to use specific versions. It _is_ a pain, because of how go get works, but it makes things fundamentally more dependable in my view.

> I'm not planning on doing that.

It's not about _your_ plans, it's about the sum of all the plans of everyone else you depend on, from the maintainers of other codebases, to the contributors that they chose to take PRs from, to the services they depend on, etc.

And, any of these people may die at any point. I like building (and depending on) things designed to last beyond the lifetime (or interest-lifetime) of the author.

> If I stop maintaining my code, it's as good as deleted.

I disagree-- your code may be useful decades after you stop. Code... does that...

I think it a valuable exercise to look through the dates at which all the tools we use on a daily bases were last committed to, maintained, re-packaged, etc. Many of the tools + protocols I use every day have been around longer than ... me. Most haven't been significantly changed for over a decade. Most have their entire source trees locked in independent locations so that users can reliably reproduce compilations without fear.

Unfortunately, in open source, the world doesn't move in lock-step. We do not have the same level of accountability and responsibility present in a large company. The "one source tree at the bleeding edge" approach fails in the presence of per-repo ACLs, hard-coded urls, etc.

> Dependency management is a non-trivial, interesting subject and I've love to talk more about it if you wish. But I'm having a lot of success with my approach for my personal code.

Fair enough :) -- its your code, do as you wish. I just cannot depend on it. You might be the best maintainer in the world but I'd have to trust every link in the chain instead of just you.


(btw, not all of my code is as well maintained as i want it to be-- you'll find lots of my code still links to the latest versions of things. this will change soon).

**Comment by shurcooL** [comment]
Thank you for explaining your perspective. You make many good and valid points, and I agree with those. I've learned from it.

You've also made some points I disagree with. I think it's related to us having some different goals/priorities regarding some things.

Again, thanks for sharing your view.
