### ISSUE TITLE
Backslash in image links are removed 

### ISSUE THREAD

**Issue by MintyOwl** [shurcooL/markdownfmt#35]
**Before** `markdownfmt`

`![Image Alt Message](path\to\image "IMAGE TITLE")`

**After** `markdownfmt`

`![Image Alt Message](pathtoimage "IMAGE TITLE")`

**Comment by shurcooL** [comment]
Hi, thanks for reporting.

Markdown uses `\` to escape characters. For example, typing `\<a\>` results in \<a\>, instead of it being interpreted as a real anchor tag. See:

https://daringfireball.net/projects/markdown/syntax#backslash

As a result, in order to have the backslash itself as a character, you need to escape it with `\\`.

So instead of writing `path\to\image`, you need to write `path\\to\\image`, otherwise it gets interpreted as `pathtoimage`.

That said, `markdownfmt` has a bug in that it doesn't preserve that escaping, so the real bug is that doing this:

```
![Image Alt Message](path\\to\\image "IMAGE TITLE")
```

Becomes:

```
![Image Alt Message](path\to\image "IMAGE TITLE")
```

**Comment by MintyOwl** [comment]
Hi there,

It seems the bug is NOT in your code. Its probably the blackfriday engine, removing the slashes.

[Reported](https://github.com/russross/blackfriday/issues/333)

**Comment by shurcooL** [comment]
Did you read my reply above?

> I tested out your new commit but same results as before.

What exactly did you test?

**Comment by MintyOwl** [comment]
Yes, your solution works, I put double slash and the problem goes away. However I feel, links with backslash should be escaped imperatively in markdown.
